export const ImportMap = {
  imports: {
    clsx: "https://cdn.jsdelivr.net/npm/clsx@2.1.1/dist/clsx.mjs",
    "clsx/lite": "https://cdn.jsdelivr.net/npm/clsx@2.1.1/dist/lite.mjs",
    "esm-env": "https://cdn.jsdelivr.net/npm/esm-env@1.2.2/index.js",
    "esm-env/browser": "https://cdn.jsdelivr.net/npm/esm-env@1.2.2/true.js",
    "esm-env/development":
      "https://cdn.jsdelivr.net/npm/esm-env@1.2.2/false.js",
    "esm-env/node": "https://cdn.jsdelivr.net/npm/esm-env@1.2.2/false.js",
    svelte: "https://unpkg.com/svelte@5.26.2/src/index-client.js",
    "svelte/html-tree-validation":
      "https://unpkg.com/svelte@5.26.2/src/html-tree-validation.js",
    "svelte/index-client":
      "https://unpkg.com/svelte@5.26.2/src/index-client.js",
    "svelte/internal/disclose-version":
      "https://unpkg.com/svelte@5.26.2/src/internal/disclose-version.js",
    "svelte/internal/server/hydration":
      "https://unpkg.com/svelte@5.26.2/src/internal/server/hydration.js",
    "svelte/internal/server/context":
      "https://unpkg.com/svelte@5.26.2/src/internal/server/context.js",
    "svelte/internal/server/payload":
      "https://unpkg.com/svelte@5.26.2/src/internal/server/payload.js",
    "svelte/internal/server/dev":
      "https://unpkg.com/svelte@5.26.2/src/internal/server/dev.js",
    "svelte/internal/server/blocks/snippet":
      "https://unpkg.com/svelte@5.26.2/src/internal/server/blocks/snippet.js",
    "svelte/internal/server/blocks/html":
      "https://unpkg.com/svelte@5.26.2/src/internal/server/blocks/html.js",
    "svelte/internal/server":
      "https://unpkg.com/svelte@5.26.2/src/internal/server/index.js",
    "svelte/internal/server/errors":
      "https://unpkg.com/svelte@5.26.2/src/internal/server/errors.js",
    "svelte/internal/client":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/index.js",
    "svelte/internal/client/dev/validation":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dev/validation.js",
    "svelte/internal/client/dev/css":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dev/css.js",
    "svelte/internal/client/dev/hmr":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dev/hmr.js",
    "svelte/internal/client/dev/assign":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dev/assign.js",
    "svelte/internal/client/dev/inspect":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dev/inspect.js",
    "svelte/internal/client/dev/elements":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dev/elements.js",
    "svelte/internal/client/dev/ownership":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dev/ownership.js",
    "svelte/internal/client/dev/legacy":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dev/legacy.js",
    "svelte/internal/client/dev/tracing":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dev/tracing.js",
    "svelte/internal/client/dev/console-log":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dev/console-log.js",
    "svelte/internal/client/dev/equality":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dev/equality.js",
    "svelte/internal/client/validate":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/validate.js",
    "svelte/internal/client/timing":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/timing.js",
    "svelte/internal/client/context":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/context.js",
    "svelte/internal/client/dom/task":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/task.js",
    "svelte/internal/client/dom/blocks/await":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/blocks/await.js",
    "svelte/internal/client/dom/blocks/key":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/blocks/key.js",
    "svelte/internal/client/dom/blocks/svelte-head":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/blocks/svelte-head.js",
    "svelte/internal/client/dom/blocks/if":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/blocks/if.js",
    "svelte/internal/client/dom/blocks/snippet":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/blocks/snippet.js",
    "svelte/internal/client/dom/blocks/css-props":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/blocks/css-props.js",
    "svelte/internal/client/dom/blocks/each":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/blocks/each.js",
    "svelte/internal/client/dom/blocks/boundary":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/blocks/boundary.js",
    "svelte/internal/client/dom/blocks/html":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/blocks/html.js",
    "svelte/internal/client/dom/blocks/svelte-element":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/blocks/svelte-element.js",
    "svelte/internal/client/dom/blocks/slot":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/blocks/slot.js",
    "svelte/internal/client/dom/blocks/svelte-component":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/blocks/svelte-component.js",
    "svelte/internal/client/dom/operations":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/operations.js",
    "svelte/internal/client/dom/reconciler":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/reconciler.js",
    "svelte/internal/client/dom/legacy/lifecycle":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/legacy/lifecycle.js",
    "svelte/internal/client/dom/legacy/misc":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/legacy/misc.js",
    "svelte/internal/client/dom/legacy/event-modifiers":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/legacy/event-modifiers.js",
    "svelte/internal/client/dom/template":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/template.js",
    "svelte/internal/client/dom/hydration":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/hydration.js",
    "svelte/internal/client/dom/elements/class":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/elements/class.js",
    "svelte/internal/client/dom/elements/custom-element":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/elements/custom-element.js",
    "svelte/internal/client/dom/elements/bindings/size":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/elements/bindings/size.js",
    "svelte/internal/client/dom/elements/bindings/navigator":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/elements/bindings/navigator.js",
    "svelte/internal/client/dom/elements/bindings/window":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/elements/bindings/window.js",
    "svelte/internal/client/dom/elements/bindings/media":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/elements/bindings/media.js",
    "svelte/internal/client/dom/elements/bindings/select":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/elements/bindings/select.js",
    "svelte/internal/client/dom/elements/bindings/shared":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/elements/bindings/shared.js",
    "svelte/internal/client/dom/elements/bindings/input":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/elements/bindings/input.js",
    "svelte/internal/client/dom/elements/bindings/this":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/elements/bindings/this.js",
    "svelte/internal/client/dom/elements/bindings/universal":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/elements/bindings/universal.js",
    "svelte/internal/client/dom/elements/bindings/document":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/elements/bindings/document.js",
    "svelte/internal/client/dom/elements/bindings/props":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/elements/bindings/props.js",
    "svelte/internal/client/dom/elements/style":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/elements/style.js",
    "svelte/internal/client/dom/elements/events":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/elements/events.js",
    "svelte/internal/client/dom/elements/transitions":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/elements/transitions.js",
    "svelte/internal/client/dom/elements/misc":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/elements/misc.js",
    "svelte/internal/client/dom/elements/attributes":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/elements/attributes.js",
    "svelte/internal/client/dom/elements/actions":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/elements/actions.js",
    "svelte/internal/client/dom/css":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/dom/css.js",
    "svelte/internal/client/reactivity/sources":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/reactivity/sources.js",
    "svelte/internal/client/reactivity/props":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/reactivity/props.js",
    "svelte/internal/client/reactivity/equality":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/reactivity/equality.js",
    "svelte/internal/client/reactivity/store":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/reactivity/store.js",
    "svelte/internal/client/reactivity/effects":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/reactivity/effects.js",
    "svelte/internal/client/reactivity/deriveds":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/reactivity/deriveds.js",
    "svelte/internal/client/proxy":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/proxy.js",
    "svelte/internal/client/warnings":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/warnings.js",
    "svelte/internal/client/loop":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/loop.js",
    "svelte/internal/client/errors":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/errors.js",
    "svelte/internal/client/runtime":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/runtime.js",
    "svelte/internal/client/render":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/render.js",
    "svelte/internal/client/constants":
      "https://unpkg.com/svelte@5.26.2/src/internal/client/constants.js",
    "svelte/internal/flags/tracing":
      "https://unpkg.com/svelte@5.26.2/src/internal/flags/tracing.js",
    "svelte/internal/flags/legacy":
      "https://unpkg.com/svelte@5.26.2/src/internal/flags/legacy.js",
    "svelte/internal/flags":
      "https://unpkg.com/svelte@5.26.2/src/internal/flags/index.js",
    "svelte/internal/shared/attributes":
      "https://unpkg.com/svelte@5.26.2/src/internal/shared/attributes.js",
    "svelte/internal/shared/errors":
      "https://unpkg.com/svelte@5.26.2/src/internal/shared/errors.js",
    "svelte/internal/shared/clone":
      "https://unpkg.com/svelte@5.26.2/src/internal/shared/clone.js",
    "svelte/internal/shared/validate":
      "https://unpkg.com/svelte@5.26.2/src/internal/shared/validate.js",
    "svelte/internal/shared/warnings":
      "https://unpkg.com/svelte@5.26.2/src/internal/shared/warnings.js",
    "svelte/internal/shared/utils":
      "https://unpkg.com/svelte@5.26.2/src/internal/shared/utils.js",
    "svelte/internal":
      "https://unpkg.com/svelte@5.26.2/src/internal/index.js",
    "svelte/escaping":
      "https://unpkg.com/svelte@5.26.2/src/escaping.js",
    "svelte/index-server":
      "https://unpkg.com/svelte@5.26.2/src/index-server.js",
    "svelte/legacy/legacy-server":
      "https://unpkg.com/svelte@5.26.2/src/legacy/legacy-server.js",
    "svelte/legacy/legacy-client":
      "https://unpkg.com/svelte@5.26.2/src/legacy/legacy-client.js",
    "svelte/utils": "https://unpkg.com/svelte@5.26.2/src/utils.js",
    "svelte/motion/spring":
      "https://unpkg.com/svelte@5.26.2/src/motion/spring.js",
    "svelte/motion/utils":
      "https://unpkg.com/svelte@5.26.2/src/motion/utils.js",
    "svelte/motion":
      "https://unpkg.com/svelte@5.26.2/src/motion/index.js",
    "svelte/motion/tweened":
      "https://unpkg.com/svelte@5.26.2/src/motion/tweened.js",
    "svelte/easing":
      "https://unpkg.com/svelte@5.26.2/src/easing/index.js",
    "svelte/transition":
      "https://unpkg.com/svelte@5.26.2/src/transition/index.js",
    "svelte/server":
      "https://unpkg.com/svelte@5.26.2/src/server/index.js",
    "svelte/compiler/migrate":
      "https://unpkg.com/svelte@5.26.2/src/compiler/migrate/index.js",
    "svelte/compiler/warnings":
      "https://unpkg.com/svelte@5.26.2/src/compiler/warnings.js",
    "svelte/compiler/errors":
      "https://unpkg.com/svelte@5.26.2/src/compiler/errors.js",
    "svelte/compiler/preprocess":
      "https://unpkg.com/svelte@5.26.2/src/compiler/preprocess/index.js",
    "svelte/compiler/preprocess/replace_in_code":
      "https://unpkg.com/svelte@5.26.2/src/compiler/preprocess/replace_in_code.js",
    "svelte/compiler/preprocess/decode_sourcemap":
      "https://unpkg.com/svelte@5.26.2/src/compiler/preprocess/decode_sourcemap.js",
    "svelte/compiler":
      "https://unpkg.com/svelte@5.26.2/src/compiler/index.js",
    "svelte/compiler/state":
      "https://unpkg.com/svelte@5.26.2/src/compiler/state.js",
    "svelte/compiler/validate-options":
      "https://unpkg.com/svelte@5.26.2/src/compiler/validate-options.js",
    "svelte/compiler/legacy":
      "https://unpkg.com/svelte@5.26.2/src/compiler/legacy.js",
    "svelte/compiler/utils/mapped_code":
      "https://unpkg.com/svelte@5.26.2/src/compiler/utils/mapped_code.js",
    "svelte/compiler/utils/slot":
      "https://unpkg.com/svelte@5.26.2/src/compiler/utils/slot.js",
    "svelte/compiler/utils/builders":
      "https://unpkg.com/svelte@5.26.2/src/compiler/utils/builders.js",
    "svelte/compiler/utils/compile_diagnostic":
      "https://unpkg.com/svelte@5.26.2/src/compiler/utils/compile_diagnostic.js",
    "svelte/compiler/utils/ast":
      "https://unpkg.com/svelte@5.26.2/src/compiler/utils/ast.js",
    "svelte/compiler/utils/assert":
      "https://unpkg.com/svelte@5.26.2/src/compiler/utils/assert.js",
    "svelte/compiler/utils/sanitize_template_string":
      "https://unpkg.com/svelte@5.26.2/src/compiler/utils/sanitize_template_string.js",
    "svelte/compiler/utils/string":
      "https://unpkg.com/svelte@5.26.2/src/compiler/utils/string.js",
    "svelte/compiler/utils/extract_svelte_ignore":
      "https://unpkg.com/svelte@5.26.2/src/compiler/utils/extract_svelte_ignore.js",
    "svelte/compiler/utils/push_array":
      "https://unpkg.com/svelte@5.26.2/src/compiler/utils/push_array.js",
    "svelte/compiler/phases/nodes":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/nodes.js",
    "svelte/compiler/phases/patterns":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/patterns.js",
    "svelte/compiler/phases/scope":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/scope.js",
    "svelte/compiler/phases/1-parse/utils/html":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/1-parse/utils/html.js",
    "svelte/compiler/phases/1-parse/utils/create":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/1-parse/utils/create.js",
    "svelte/compiler/phases/1-parse/utils/entities":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/1-parse/utils/entities.js",
    "svelte/compiler/phases/1-parse/utils/fuzzymatch":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/1-parse/utils/fuzzymatch.js",
    "svelte/compiler/phases/1-parse/utils/bracket":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/1-parse/utils/bracket.js",
    "svelte/compiler/phases/1-parse/remove_typescript_nodes":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/1-parse/remove_typescript_nodes.js",
    "svelte/compiler/phases/1-parse/acorn":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/1-parse/acorn.js",
    "svelte/compiler/phases/1-parse/read/context":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/1-parse/read/context.js",
    "svelte/compiler/phases/1-parse/read/script":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/1-parse/read/script.js",
    "svelte/compiler/phases/1-parse/read/options":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/1-parse/read/options.js",
    "svelte/compiler/phases/1-parse/read/style":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/1-parse/read/style.js",
    "svelte/compiler/phases/1-parse/read/expression":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/1-parse/read/expression.js",
    "svelte/compiler/phases/1-parse":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/1-parse/index.js",
    "svelte/compiler/phases/1-parse/state/text":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/1-parse/state/text.js",
    "svelte/compiler/phases/1-parse/state/fragment":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/1-parse/state/fragment.js",
    "svelte/compiler/phases/1-parse/state/element":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/1-parse/state/element.js",
    "svelte/compiler/phases/1-parse/state/tag":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/1-parse/state/tag.js",
    "svelte/compiler/phases/3-transform":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/index.js",
    "svelte/compiler/phases/3-transform/shared/assignments":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/shared/assignments.js",
    "svelte/compiler/phases/3-transform/css":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/css/index.js",
    "svelte/compiler/phases/3-transform/utils":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/utils.js",
    "svelte/compiler/phases/3-transform/server/transform-server":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/server/transform-server.js",
    "svelte/compiler/phases/3-transform/server/visitors/SnippetBlock":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/server/visitors/SnippetBlock.js",
    "svelte/compiler/phases/3-transform/server/visitors/EachBlock":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/server/visitors/EachBlock.js",
    "svelte/compiler/phases/3-transform/server/visitors/HtmlTag":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/server/visitors/HtmlTag.js",
    "svelte/compiler/phases/3-transform/server/visitors/PropertyDefinition":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/server/visitors/PropertyDefinition.js",
    "svelte/compiler/phases/3-transform/server/visitors/CallExpression":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/server/visitors/CallExpression.js",
    "svelte/compiler/phases/3-transform/server/visitors/SvelteFragment":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/server/visitors/SvelteFragment.js",
    "svelte/compiler/phases/3-transform/server/visitors/SpreadAttribute":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/server/visitors/SpreadAttribute.js",
    "svelte/compiler/phases/3-transform/server/visitors/KeyBlock":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/server/visitors/KeyBlock.js",
    "svelte/compiler/phases/3-transform/server/visitors/SvelteComponent":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/server/visitors/SvelteComponent.js",
    "svelte/compiler/phases/3-transform/server/visitors/IfBlock":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/server/visitors/IfBlock.js",
    "svelte/compiler/phases/3-transform/server/visitors/MemberExpression":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/server/visitors/MemberExpression.js",
    "svelte/compiler/phases/3-transform/server/visitors/RegularElement":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/server/visitors/RegularElement.js",
    "svelte/compiler/phases/3-transform/server/visitors/ExpressionStatement":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/server/visitors/ExpressionStatement.js",
    "svelte/compiler/phases/3-transform/server/visitors/SvelteSelf":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/server/visitors/SvelteSelf.js",
    "svelte/compiler/phases/3-transform/server/visitors/Identifier":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/server/visitors/Identifier.js",
    "svelte/compiler/phases/3-transform/server/visitors/VariableDeclaration":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/server/visitors/VariableDeclaration.js",
    "svelte/compiler/phases/3-transform/server/visitors/ClassBody":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/server/visitors/ClassBody.js",
    "svelte/compiler/phases/3-transform/server/visitors/SvelteBoundary":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/server/visitors/SvelteBoundary.js",
    "svelte/compiler/phases/3-transform/server/visitors/Component":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/server/visitors/Component.js",
    "svelte/compiler/phases/3-transform/server/visitors/UpdateExpression":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/server/visitors/UpdateExpression.js",
    "svelte/compiler/phases/3-transform/server/visitors/DebugTag":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/server/visitors/DebugTag.js",
    "svelte/compiler/phases/3-transform/server/visitors/RenderTag":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/server/visitors/RenderTag.js",
    "svelte/compiler/phases/3-transform/server/visitors/Fragment":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/server/visitors/Fragment.js",
    "svelte/compiler/phases/3-transform/server/visitors/ConstTag":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/server/visitors/ConstTag.js",
    "svelte/compiler/phases/3-transform/server/visitors/shared/component":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/server/visitors/shared/component.js",
    "svelte/compiler/phases/3-transform/server/visitors/shared/utils":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/server/visitors/shared/utils.js",
    "svelte/compiler/phases/3-transform/server/visitors/shared/element":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/server/visitors/shared/element.js",
    "svelte/compiler/phases/3-transform/server/visitors/AwaitBlock":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/server/visitors/AwaitBlock.js",
    "svelte/compiler/phases/3-transform/server/visitors/SvelteHead":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/server/visitors/SvelteHead.js",
    "svelte/compiler/phases/3-transform/server/visitors/SvelteElement":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/server/visitors/SvelteElement.js",
    "svelte/compiler/phases/3-transform/server/visitors/SlotElement":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/server/visitors/SlotElement.js",
    "svelte/compiler/phases/3-transform/server/visitors/TitleElement":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/server/visitors/TitleElement.js",
    "svelte/compiler/phases/3-transform/server/visitors/LabeledStatement":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/server/visitors/LabeledStatement.js",
    "svelte/compiler/phases/3-transform/server/visitors/AssignmentExpression":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/server/visitors/AssignmentExpression.js",
    "svelte/compiler/phases/3-transform/client/utils":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/utils.js",
    "svelte/compiler/phases/3-transform/client/transform-client":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/transform-client.js",
    "svelte/compiler/phases/3-transform/client/visitors/SlotElement":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/SlotElement.js",
    "svelte/compiler/phases/3-transform/client/visitors/MemberExpression":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/MemberExpression.js",
    "svelte/compiler/phases/3-transform/client/visitors/AnimateDirective":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/AnimateDirective.js",
    "svelte/compiler/phases/3-transform/client/visitors/SvelteWindow":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/SvelteWindow.js",
    "svelte/compiler/phases/3-transform/client/visitors/BinaryExpression":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/BinaryExpression.js",
    "svelte/compiler/phases/3-transform/client/visitors/SvelteComponent":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/SvelteComponent.js",
    "svelte/compiler/phases/3-transform/client/visitors/SvelteHead":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/SvelteHead.js",
    "svelte/compiler/phases/3-transform/client/visitors/SpreadAttribute":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/SpreadAttribute.js",
    "svelte/compiler/phases/3-transform/client/visitors/AwaitBlock":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/AwaitBlock.js",
    "svelte/compiler/phases/3-transform/client/visitors/SnippetBlock":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/SnippetBlock.js",
    "svelte/compiler/phases/3-transform/client/visitors/AssignmentExpression":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/AssignmentExpression.js",
    "svelte/compiler/phases/3-transform/client/visitors/SvelteElement":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/SvelteElement.js",
    "svelte/compiler/phases/3-transform/client/visitors/EachBlock":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/EachBlock.js",
    "svelte/compiler/phases/3-transform/client/visitors/KeyBlock":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/KeyBlock.js",
    "svelte/compiler/phases/3-transform/client/visitors/ArrowFunctionExpression":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/ArrowFunctionExpression.js",
    "svelte/compiler/phases/3-transform/client/visitors/UseDirective":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/UseDirective.js",
    "svelte/compiler/phases/3-transform/client/visitors/IfBlock":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/IfBlock.js",
    "svelte/compiler/phases/3-transform/client/visitors/CallExpression":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/CallExpression.js",
    "svelte/compiler/phases/3-transform/client/visitors/SvelteFragment":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/SvelteFragment.js",
    "svelte/compiler/phases/3-transform/client/visitors/OnDirective":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/OnDirective.js",
    "svelte/compiler/phases/3-transform/client/visitors/SvelteBody":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/SvelteBody.js",
    "svelte/compiler/phases/3-transform/client/visitors/BindDirective":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/BindDirective.js",
    "svelte/compiler/phases/3-transform/client/visitors/HtmlTag":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/HtmlTag.js",
    "svelte/compiler/phases/3-transform/client/visitors/RegularElement":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/RegularElement.js",
    "svelte/compiler/phases/3-transform/client/visitors/Comment":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/Comment.js",
    "svelte/compiler/phases/3-transform/client/visitors/Attribute":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/Attribute.js",
    "svelte/compiler/phases/3-transform/client/visitors/Identifier":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/Identifier.js",
    "svelte/compiler/phases/3-transform/client/visitors/BlockStatement":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/BlockStatement.js",
    "svelte/compiler/phases/3-transform/client/visitors/SvelteSelf":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/SvelteSelf.js",
    "svelte/compiler/phases/3-transform/client/visitors/FunctionExpression":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/FunctionExpression.js",
    "svelte/compiler/phases/3-transform/client/visitors/ExportNamedDeclaration":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/ExportNamedDeclaration.js",
    "svelte/compiler/phases/3-transform/client/visitors/BreakStatement":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/BreakStatement.js",
    "svelte/compiler/phases/3-transform/client/visitors/UpdateExpression":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/UpdateExpression.js",
    "svelte/compiler/phases/3-transform/client/visitors/Program":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/Program.js",
    "svelte/compiler/phases/3-transform/client/visitors/shared/declarations":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/shared/declarations.js",
    "svelte/compiler/phases/3-transform/client/visitors/shared/special_element":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/shared/special_element.js",
    "svelte/compiler/phases/3-transform/client/visitors/shared/component":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/shared/component.js",
    "svelte/compiler/phases/3-transform/client/visitors/shared/utils":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/shared/utils.js",
    "svelte/compiler/phases/3-transform/client/visitors/shared/events":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/shared/events.js",
    "svelte/compiler/phases/3-transform/client/visitors/shared/element":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/shared/element.js",
    "svelte/compiler/phases/3-transform/client/visitors/shared/function":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/shared/function.js",
    "svelte/compiler/phases/3-transform/client/visitors/shared/fragment":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/shared/fragment.js",
    "svelte/compiler/phases/3-transform/client/visitors/TransitionDirective":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/TransitionDirective.js",
    "svelte/compiler/phases/3-transform/client/visitors/ImportDeclaration":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/ImportDeclaration.js",
    "svelte/compiler/phases/3-transform/client/visitors/LetDirective":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/LetDirective.js",
    "svelte/compiler/phases/3-transform/client/visitors/ExpressionStatement":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/ExpressionStatement.js",
    "svelte/compiler/phases/3-transform/client/visitors/FunctionDeclaration":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/FunctionDeclaration.js",
    "svelte/compiler/phases/3-transform/client/visitors/SvelteDocument":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/SvelteDocument.js",
    "svelte/compiler/phases/3-transform/client/visitors/Component":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/Component.js",
    "svelte/compiler/phases/3-transform/client/visitors/SvelteBoundary":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/SvelteBoundary.js",
    "svelte/compiler/phases/3-transform/client/visitors/LabeledStatement":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/LabeledStatement.js",
    "svelte/compiler/phases/3-transform/client/visitors/ClassBody":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/ClassBody.js",
    "svelte/compiler/phases/3-transform/client/visitors/Fragment":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/Fragment.js",
    "svelte/compiler/phases/3-transform/client/visitors/ConstTag":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/ConstTag.js",
    "svelte/compiler/phases/3-transform/client/visitors/RenderTag":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/RenderTag.js",
    "svelte/compiler/phases/3-transform/client/visitors/VariableDeclaration":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/VariableDeclaration.js",
    "svelte/compiler/phases/3-transform/client/visitors/TitleElement":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/TitleElement.js",
    "svelte/compiler/phases/3-transform/client/visitors/DebugTag":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/3-transform/client/visitors/DebugTag.js",
    "svelte/compiler/phases/css":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/css.js",
    "svelte/compiler/phases/bindings":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/bindings.js",
    "svelte/compiler/phases/2-analyze/visitors/TaggedTemplateExpression":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/TaggedTemplateExpression.js",
    "svelte/compiler/phases/2-analyze/visitors/KeyBlock":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/KeyBlock.js",
    "svelte/compiler/phases/2-analyze/visitors/SvelteDocument":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/SvelteDocument.js",
    "svelte/compiler/phases/2-analyze/visitors/SvelteElement":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/SvelteElement.js",
    "svelte/compiler/phases/2-analyze/visitors/ExportNamedDeclaration":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/ExportNamedDeclaration.js",
    "svelte/compiler/phases/2-analyze/visitors/SvelteBoundary":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/SvelteBoundary.js",
    "svelte/compiler/phases/2-analyze/visitors/BindDirective":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/BindDirective.js",
    "svelte/compiler/phases/2-analyze/visitors/MemberExpression":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/MemberExpression.js",
    "svelte/compiler/phases/2-analyze/visitors/TitleElement":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/TitleElement.js",
    "svelte/compiler/phases/2-analyze/visitors/OnDirective":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/OnDirective.js",
    "svelte/compiler/phases/2-analyze/visitors/ClassDirective":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/ClassDirective.js",
    "svelte/compiler/phases/2-analyze/visitors/ExpressionStatement":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/ExpressionStatement.js",
    "svelte/compiler/phases/2-analyze/visitors/FunctionDeclaration":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/FunctionDeclaration.js",
    "svelte/compiler/phases/2-analyze/visitors/ExportSpecifier":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/ExportSpecifier.js",
    "svelte/compiler/phases/2-analyze/visitors/EachBlock":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/EachBlock.js",
    "svelte/compiler/phases/2-analyze/visitors/SvelteSelf":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/SvelteSelf.js",
    "svelte/compiler/phases/2-analyze/visitors/TransitionDirective":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/TransitionDirective.js",
    "svelte/compiler/phases/2-analyze/visitors/ClassDeclaration":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/ClassDeclaration.js",
    "svelte/compiler/phases/2-analyze/visitors/IfBlock":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/IfBlock.js",
    "svelte/compiler/phases/2-analyze/visitors/SlotElement":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/SlotElement.js",
    "svelte/compiler/phases/2-analyze/visitors/Text":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/Text.js",
    "svelte/compiler/phases/2-analyze/visitors/Identifier":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/Identifier.js",
    "svelte/compiler/phases/2-analyze/visitors/VariableDeclarator":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/VariableDeclarator.js",
    "svelte/compiler/phases/2-analyze/visitors/HtmlTag":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/HtmlTag.js",
    "svelte/compiler/phases/2-analyze/visitors/LetDirective":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/LetDirective.js",
    "svelte/compiler/phases/2-analyze/visitors/StyleDirective":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/StyleDirective.js",
    "svelte/compiler/phases/2-analyze/visitors/UpdateExpression":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/UpdateExpression.js",
    "svelte/compiler/phases/2-analyze/visitors/shared/component":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/shared/component.js",
    "svelte/compiler/phases/2-analyze/visitors/shared/special-element":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/shared/special-element.js",
    "svelte/compiler/phases/2-analyze/visitors/shared/attribute":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/shared/attribute.js",
    "svelte/compiler/phases/2-analyze/visitors/shared/function":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/shared/function.js",
    "svelte/compiler/phases/2-analyze/visitors/shared/utils":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/shared/utils.js",
    "svelte/compiler/phases/2-analyze/visitors/shared/fragment":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/shared/fragment.js",
    "svelte/compiler/phases/2-analyze/visitors/shared/element":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/shared/element.js",
    "svelte/compiler/phases/2-analyze/visitors/shared/snippets":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/shared/snippets.js",
    "svelte/compiler/phases/2-analyze/visitors/shared/a11y":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/shared/a11y.js",
    "svelte/compiler/phases/2-analyze/visitors/ArrowFunctionExpression":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/ArrowFunctionExpression.js",
    "svelte/compiler/phases/2-analyze/visitors/SpreadElement":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/SpreadElement.js",
    "svelte/compiler/phases/2-analyze/visitors/CallExpression":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/CallExpression.js",
    "svelte/compiler/phases/2-analyze/visitors/UseDirective":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/UseDirective.js",
    "svelte/compiler/phases/2-analyze/visitors/ConstTag":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/ConstTag.js",
    "svelte/compiler/phases/2-analyze/visitors/RenderTag":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/RenderTag.js",
    "svelte/compiler/phases/2-analyze/visitors/ClassBody":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/ClassBody.js",
    "svelte/compiler/phases/2-analyze/visitors/SvelteFragment":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/SvelteFragment.js",
    "svelte/compiler/phases/2-analyze/visitors/ImportDeclaration":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/ImportDeclaration.js",
    "svelte/compiler/phases/2-analyze/visitors/ExportDefaultDeclaration":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/ExportDefaultDeclaration.js",
    "svelte/compiler/phases/2-analyze/visitors/Component":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/Component.js",
    "svelte/compiler/phases/2-analyze/visitors/SvelteBody":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/SvelteBody.js",
    "svelte/compiler/phases/2-analyze/visitors/DebugTag":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/DebugTag.js",
    "svelte/compiler/phases/2-analyze/visitors/RegularElement":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/RegularElement.js",
    "svelte/compiler/phases/2-analyze/visitors/FunctionExpression":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/FunctionExpression.js",
    "svelte/compiler/phases/2-analyze/visitors/AssignmentExpression":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/AssignmentExpression.js",
    "svelte/compiler/phases/2-analyze/visitors/NewExpression":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/NewExpression.js",
    "svelte/compiler/phases/2-analyze/visitors/ExpressionTag":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/ExpressionTag.js",
    "svelte/compiler/phases/2-analyze/visitors/SvelteWindow":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/SvelteWindow.js",
    "svelte/compiler/phases/2-analyze/visitors/AwaitBlock":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/AwaitBlock.js",
    "svelte/compiler/phases/2-analyze/visitors/SvelteHead":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/SvelteHead.js",
    "svelte/compiler/phases/2-analyze/visitors/SpreadAttribute":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/SpreadAttribute.js",
    "svelte/compiler/phases/2-analyze/visitors/Attribute":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/Attribute.js",
    "svelte/compiler/phases/2-analyze/visitors/SnippetBlock":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/SnippetBlock.js",
    "svelte/compiler/phases/2-analyze/visitors/LabeledStatement":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/LabeledStatement.js",
    "svelte/compiler/phases/2-analyze/visitors/SvelteComponent":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/visitors/SvelteComponent.js",
    "svelte/compiler/phases/2-analyze/utils/check_graph_for_cycles":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/utils/check_graph_for_cycles.js",
    "svelte/compiler/phases/2-analyze":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/index.js",
    "svelte/compiler/phases/2-analyze/css/css-prune":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/css/css-prune.js",
    "svelte/compiler/phases/2-analyze/css/css-warn":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/css/css-warn.js",
    "svelte/compiler/phases/2-analyze/css/css-analyze":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/css/css-analyze.js",
    "svelte/compiler/phases/2-analyze/css/utils":
      "https://unpkg.com/svelte@5.26.2/src/compiler/phases/2-analyze/css/utils.js",
    "svelte/reactivity/date":
      "https://unpkg.com/svelte@5.26.2/src/reactivity/date.js",
    "svelte/reactivity/window":
      "https://unpkg.com/svelte@5.26.2/src/reactivity/window/index.js",
    "svelte/reactivity/create-subscriber":
      "https://unpkg.com/svelte@5.26.2/src/reactivity/create-subscriber.js",
    "svelte/reactivity/utils":
      "https://unpkg.com/svelte@5.26.2/src/reactivity/utils.js",
    "svelte/reactivity/url":
      "https://unpkg.com/svelte@5.26.2/src/reactivity/url.js",
    "svelte/reactivity/url-search-params":
      "https://unpkg.com/svelte@5.26.2/src/reactivity/url-search-params.js",
    "svelte/reactivity/reactive-value":
      "https://unpkg.com/svelte@5.26.2/src/reactivity/reactive-value.js",
    "svelte/reactivity/set":
      "https://unpkg.com/svelte@5.26.2/src/reactivity/set.js",
    "svelte/reactivity/media-query":
      "https://unpkg.com/svelte@5.26.2/src/reactivity/media-query.js",
    "svelte/reactivity/map":
      "https://unpkg.com/svelte@5.26.2/src/reactivity/map.js",
    "svelte/reactivity/index-client":
      "https://unpkg.com/svelte@5.26.2/src/reactivity/index-client.js",
    "svelte/reactivity/index-server":
      "https://unpkg.com/svelte@5.26.2/src/reactivity/index-server.js",
    "svelte/store/utils":
      "https://unpkg.com/svelte@5.26.2/src/store/utils.js",
    "svelte/store/shared":
      "https://unpkg.com/svelte@5.26.2/src/store/shared/index.js",
    "svelte/store/index-client":
      "https://unpkg.com/svelte@5.26.2/src/store/index-client.js",
    "svelte/store/index-server":
      "https://unpkg.com/svelte@5.26.2/src/store/index-server.js",
    "svelte/constants":
      "https://unpkg.com/svelte@5.26.2/src/constants.js",
    "svelte/animate":
      "https://unpkg.com/svelte@5.26.2/src/animate/index.js",
    "svelte/events":
      "https://unpkg.com/svelte@5.26.2/src/events/index.js",
    "svelte/version":
      "https://unpkg.com/svelte@5.26.2/src/version.js",
  },
};
